### ISSUE TITLE
Lagging ui on playing 30 fps video 

### ISSUE THREAD

**Issue by MuhammadShahzeel** [crdroidandroid/issue_tracker#435] opened 2024-06-03 17:54 UTC
### Issue type

User interface

### Device

Google pixel 4a 5g / bramble

### crDroid version

crDroid 10

### Exact version / Build date

10.5/2024-05-29

### Bug description

I just installed crDroid, and I love it! The main reason I installed crDroid is because there is an issue in the stock ROM: when a video with a frame rate of 30 fps or less plays in any app, the whole UI and the app lag a lot until I pause the video or switch to a 60 fps video. This issue occurs in the Discord app, YouTube, Google Photos, and any other app running a video with 30 fps or a GIF. Unfortunately, the issue persists even after installing crDroid. I think this might be a problem with the Pixel 4a 5G. Please help me fix this issue; it's so annoying.

### Steps to reproduce

1. Go to YouTube
2. Play some 30fps video 

### Relevant log (logcat/build log)

```shell
Don't know how to find build log
```

### Solution

I thinks its issue with refresh rate or something when a 30fps video olay whole ui become laggy .

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by 306bobby-android** [comment] 2024-06-28 15:40
This is a known bug for redfin and bramble, supposed to be fixed by Google but was never done. We are working on figuring out the fault, but since the patch was never released by Google, it's tough going


I will be closing due to known issue - needs extensive work

**Comment by MuhammadShahzeel** [comment] 2024-06-28 16:08
This is very annoying. It turns out that, like someone said earlier, it
likely has something to do with the Adaptive Refresh Rate feature, even
though these devices don't support it. Notably, the issue arises when
watching video at 30fps, any resolution, any app. If you play a 60fps
video, the issue goes away.

I thought that there's probably a way to force the refresh rate without
Settings. Did some research and found some ADB commands that appear to
work. I ran the following commands on my Pixel 4a(5G) from my PC with
"Debugging over USB" Interestingly, the issue went away! However, only for
the System UI (Notification shade, opening app switcher, home screen
swiping, etc.). In any apps playing video, the issue still appears to
persist. Here are the commands:

adb shell settings put system min_refresh_rate 60.0

adb shell settings put system peak_refresh_rate 60.0

**Comment by 306bobby-android** [comment] 2024-06-28 17:40
Yes, you are likely right. The issue is, redfin does support adaptive refresh with it's 90hz display, and it's broken there too.

It's really annoying, and once QPR3 is released I'll take a deep dive into it. It's just hard for me as bramble is the main culprit, redfin is only occasional and barbet is fine. I only own barbet and redfin for now. I'll likely invest in a bramble for things like this

**Comment by MuhammadShahzeel** [comment] 2024-06-28 17:44
Thanks by the way when new june build released for bramble?

**Comment by 306bobby-android** [comment] 2024-07-27 16:54
This issue should now be solved in 10.6 QPR3

**Closed by 306bobby-android** 2024-07-27 16:54 UTC
Labels: bug
