### ISSUE TITLE
bug: headset problem when plugging in Poco F3 (alioth)

### ISSUE THREAD

**Issue by sirmeow1** [crdroidandroid/issue_tracker#479] opened 2024-08-08 18:28 UTC
### Issue type

Feature not working as intended

### Device

Poco F3 (Alioth)

### crDroid version

crDroid 10

### Exact version / Build date

crDroid 10.6
Android 14
Current build date: July 26, 2024

### Bug description

whenever i plug my headphone (usb-c), all videos and gif from youtube, facebook, reddit, etc. goes into slideshow. like it plays for a second, then stops, then plays again, then stops with no sound. also if i try to unplug my headset when the video is playing, the phone crashes then restarts. playing videos with no headphones is fine. playing videos with wireless earbuds is fine.

### Steps to reproduce

Step 1. Plug headphones.
Step 2. Open an app and play a video.
Step 3. Video cannot play properly.
Step 4. Unplug headphones.
Step 5. Phone crashes and restarts.

### Relevant log (logcat/build log)

```shell
i added the text file below
```

### Screenshots or videos

https://github.com/user-attachments/assets/365fbaff-85ae-4976-bae0-9526b9a1a8a4

[2024-08-09-01-14-44.txt](https://github.com/user-attachments/files/16552057/2024-08-09-01-14-44.txt)

### Solution

N/A

### Additional context

playing games if fine. no problem using the headset. audio works fine. just playing videos or gif is causing it problems. on youtube, facebook, reddit, xtwitter. also videos in phone storage

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by raystef66** [comment] 2024-08-12 11:51
Will be fixed on next update or use module for now.
[alioth_wiredheadsetFix_YT_call_12082024_raystef66.zip](https://github.com/user-attachments/files/16581120/alioth_wiredheadsetFix_YT_call_12082024_raystef66.zip)

**Closed** 2024-08-12 11:53 UTC
Labels: bug, needs-triage

**Comment by defvs** [comment] 2024-08-24 18:11
Bug seems to have reappeared, or a similar one that is;
I'm having the exact issue described.
I think it was fixed in the newer versions, right?
i've diff'ed the given module's file with mine and it's exactly the same - that is why I'm guessing the fix is already in this build.

alioth
crDroid 10.7
Build 2024-08-05

**Comment by raystef66** [comment] 2024-08-24 18:17
> Bug seems to have reappeared, or a similar one that is; I'm having the exact issue described. I think it was fixed in the newer versions, right? i've diff'ed the given module's file with mine and it's exactly the same - that is why I'm guessing the fix is already in this build.
> 
> alioth crDroid 10.7 Build 2024-08-05
> 
> Just in case: my dongle is a Fiio KA11

Tried 23.08 build?

**Comment by defvs** [comment] 2024-08-24 18:25
Oh yeah, I just noticed I'm not on latest - going to try tonight. My bad 😞

**Comment by defvs** [comment] 2024-08-24 20:22
@raystef66 edit: I am on August 23 2024 build and not 0805 as previously stated, I was reading the wrong build number off the system information.

**Comment by raystef66** [comment] 2024-08-30 18:15
@defvs   do check again on 30.08 build
But some other user confirmed to me it was still working on 23.08 build. So no clue why it shouldn't work for you.

**Comment by WINDROID-EMU** [comment] 2025-08-08 16:34
Estou na última versão da CR droid e também estou passando pelo mesmo 08-08 13:26:55.106 E/soundtrigger(1017): audio_extn_sound_trigger_update_stream_status: invalid input device 0x0, for event 3

**Comment by WINDROID-EMU** [comment] 2025-08-08 18:09
solution link file replace /vendor/etc/audio policy configuration.xml here it worked for me poco f3 alioth need root 


https://drive.google.com/file/d/1-0m9IqlTY_pF4dyLJAivg9yIIC1yGnLE/view?usp=drivesdk

**Comment by WINDROID-EMU** [comment] 2025-08-10 16:09
> > solution link file replace /vendor/etc/audio policy configuration.xml here it worked for me poco f3 alioth need root
> > 
> > https://drive.google.com/file/d/1-0m9IqlTY_pF4dyLJAivg9yIIC1yGnLE/view?usp=drivesdk
> 
> I can compare but is this the same xml as my wiredheadset.zip from above?
> Also does the issue like on Plexamp still exist?
> Cr10 or 11?

Dude, I made this XML and all the audio bugs here were resolved. I use USB-C headphones and the audio didn't work, and it was resolved for WhatsApp audios and all audio apps.

**Comment by md-safiulsadik** [comment] 2026-02-14 02:44
> solution link file replace /vendor/etc/audio policy configuration.xml here it worked for me poco f3 alioth need root
> 
> https://drive.google.com/file/d/1-0m9IqlTY_pF4dyLJAivg9yIIC1yGnLE/view?usp=drivesdk

I install your Crdroid in my Poco f3 when I connect my earbuds wasn't getting any sound, then I saw this and replace the xml fine. The problem was fixed but a new problem arised that is my volume was at it's maximum, I wasn't an able to lower my volume at all neither the device volume nor the earbuds volume. What should I do now.
