### ISSUE TITLE
bug: bluetooth headphones low quality audio in calls

### ISSUE THREAD

**Issue by cptMikky** [crdroidandroid/issue_tracker#83] opened 2023-01-03 13:41 UTC
### Issue type

Feature not working as intended

### Device

One Plus 9 pro (lemonadep)

### crDroid version

crDroid 9

### Exact version / Build date

2022-12-30

### Bug description

With bluetooth headphones Souncore Life Note 3 I have bad quality audio when in calls, both cellular and data (like Zoom). The audio distortion sounds like a mix of very low bandwidth and missing about 50 % of the packets, similar (but not quite the same) as with poor connection on Zoom/Teams/etc.

There are a few abnormalities:
- only for calls, media audio is ok
- only for the audio in headphones, recorded audio from the phone line is ok
- for both cellular calls and data calls _but_ for data calls (e.g. Zoom) _only_ when on cellular data and _not_ on WiFi
- another headset - a bigger JBL Quantum 800, works ok for both audio _and_ calls
- I wasn't able to replicate the issue with WhatsApp 

I don't have any other BT headset available to test atm.

I will provide logs when I have a chance to rig a test to prevent long and irrelevant data.

### Steps to reproduce

1. pair bluetooth headphones
2. make a call via cell or Zoom
3. optionally enable call recording and record the call
4. if 3 then compare the recorded audio quality to the audio quality received through the headphones
5. if 4 you can even play the recording through the headphones, it will be ok

### Relevant log (logcat/build log)

```shell
TBD
```

### Additional context

This issue only exists with the received audio. The microphone seems to be OK according to the other parties in the calls.

I will raise a question with Soundcore support as will and update accordingly if they prove helpful.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment] 2023-01-15 09:22
does this happen with crDroid 9.1 ?

**Comment by cptMikky** [comment] 2023-01-15 10:12
Don't know, couldn't update to 9.1, getting "crashdump mode" after reboot. Maybe related to Magisk but I haven't had the time to check yet.

**Comment by gwolf2u** [comment] 2023-01-15 10:15
> Don't know, couldn't update to 9.1, getting "crashdump mode" after reboot. Maybe related to Magisk but I haven't had the time to check yet.

Use updated boot.img from recovery button on download page

**Comment by jficz** [comment] 2023-01-15 11:41
did that, update went well, running 9.1 but the issue is still there I'm afraid. Tried re-pairing, reboots, reinstalling (and not even using) the vendor control app but the result is always the same.

**Comment by gwolf2u** [comment] 2023-01-15 11:47
Tried disabling a2dp?

**Comment by jficz** [comment] 2023-01-15 11:52
it apparently is off but I can't change it anyway:man_shrugging: 
![Screenshot_20230115-124913_Settings](https://user-images.githubusercontent.com/10010448/212538923-8b08fd24-429c-44e7-8c46-c518e07d8699.png)

**Comment by jficz** [comment] 2023-01-16 10:40
found a random cheap BT earpiece I bought years back on Aliexpress and it works ok. So the issue is somehow related either directly to Souncore Life Note 3 or to a specific piece of technology it uses (newer BT, BTLE, codecs...)

I'll ping their support and try to think of some other test scenarios.

**Comment by neobuddy89** [comment] 2023-01-17 19:07
Wait for new version based on OOS13.

**Comment by neobuddy89** [comment] 2023-01-17 19:07
If you need test version, ping me on Telegram - it's WIP stuff though.

**Comment by jficz** [comment] 2023-01-30 09:27
it _seems_ to be fixed with the latest OOS13-based crDroid, Had to disable the "Disable A2DP offload" debug switch though, as in, the switch itself is _off_ meaning A2DP offloading is presumably _enabled_

**Comment by jficz** [comment] 2023-01-30 15:00
Actually, not fixed.

First couple of cell phone calls went through OK but when I had a Zoom call it broke again as soon as I switched off wifi. Then I tried multiple reboots, setting A2DP offload off and on again, switching off and on `settings_audio_switcher` flag but I was so far unable to get a clean call again.

I tried to unpair the earbuds, delete the controll app and the repair them without the app. After that, I managed to get two cell phone calls without issues, then waited a few minutes and performed a third cell call which was, again, broken. I did nothing else with the phone between calls 2 and 3 except locking and unlocking it.

**Comment by gwolf2u** [comment] 2023-02-04 11:28
happening still?

**Comment by jficz** [comment] 2023-02-05 23:00
running build from Feb 3, reflashed whole firmware again (incl. modem) just to be sure I didn't miss anything but the problem is still there :/

**Comment by gwolf2u** [comment] 2023-02-07 16:47
can you provide a logcat for this with included BT headset address (format XX:XX:XX...) ?
run adb logcat > log.txt in terminal with phone connected to PC
try to simulate the issue again
close terminal and attach file please

**Comment by jficz** [comment] 2023-02-08 11:10
I'll try to rig a test some time this week. In the mean time, I got another reply from the support. Not sure I understand exactly what they tried to tell me though :shrug: 

> According to our engineer's reply, please know the HFP is used by the mobile terminal to make calls, and the HFP protocol itself is better than the A2DP protocol, and the sound will sound not as expected.
>
> If there is no issue with the wifi, please check your network situation. We think this has nothing to do with the product.

**Comment by gwolf2u** [comment] 2023-03-03 08:22
as of now there's no specific fix for this
this will get revisited at a later time in future android updates

**Closed by gwolf2u** 2023-03-03 08:22 UTC
Labels: bug
