### ISSUE TITLE
gps not working (wrong gapps?)

### ISSUE THREAD

**Issue by aexm33** [crdroidandroid/issue_tracker#257] opened 2023-10-06 17:27 UTC
### Issue type

Other

### Device

Poco x3 pro

### crDroid version

crDroid 9

### Exact version / Build date

9.9 2023-10-02

### Bug description

Maps not working while other apps see my location no problems.

### Steps to reproduce

When pressing on "locate my position" icon on google maps it does nothing.

### Relevant log (logcat/build log)

```shell
I have zero idea what that means.or where to copy it from.
```

### Additional context

Other apps see my location so i guess its not a gps chip problem 

_No response_

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment] 2023-10-06 17:30
now please don't be ignorant
https://github.com/crdroidandroid/crdroid_features/issues/99#issuecomment-1751139873
all the more what I wrote there, seems to prove for you
"every day people not reading and replying to same question when already asked"
also linked to a issue_tracker issue there that has been answered for same issue in 2022

closed as duplicate of #59

**Closed by gwolf2u** 2023-10-06 17:30 UTC
Labels: bug, needs-triage

**Comment by aexm33** [comment] 2023-10-06 17:32
I have I have NikGapps-core-arm64-13-20230418-signed.zip installed. Am i using the wrong gapps?

**Comment by aexm33** [comment] 2023-10-06 17:34
So what do i do now reinstall the rom?

**Comment by aexm33** [comment] 2023-10-06 17:39
Also by "everyday people " what do you mean by that?

**Comment by gwolf2u** [comment] 2023-10-06 17:40
clean install will fix it for sure
weather you're doing it or not, up to you
but again, not ROM issue

as for "Also by "everyday people " what do you mean by that?", I'll just say, let's just stop the chatting here, this is not Telegram
