### ISSUE TITLE
Live display bug in One Plus 6

### ISSUE THREAD

**Issue by C-Ubermensch** [crdroidandroid/issue_tracker#265] opened 2023-11-08 11:10 UTC
### Issue type

Feature not working as intended

### Device

ONEPLUS A6003

### crDroid version

crDroid 7

### Exact version / Build date

9.10 4 nov 2023

### Bug description

I have an One Plus 6.
In display settings there's Live Display settings and when i change to one of them, (especially from amoled gamut mode to standart or sRGB) it changes itself back into amoled gamut mode.
So it doesn't stay put, it changes modes after a while.
Something like that. 

### Steps to reproduce

1. Go settings
2. Go to display
3. Go to live display
4. Select sRGB
 After selecting it, it changes to amoled wide gamut after a while.

### Relevant log (logcat/build log)

```shell
-
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Terminator-J** [comment] 2023-11-13 17:24
So the "exact version" and "build date" suggest yes, crDroid 9.10. But you also put down crDroid 7 (android 11).
Which one is it, just to clarify?

Also, are there any particular apps like YouTube, or Google Photos, that you use that could be causing the mode switch "after a while"? I'm suspicious that it's one of these apps that tries to demand an HDR display mode if available, then it fails to switch back when exiting to a different activity...

If you could reboot, set your panel mode to something else (standard?) and then back to sRGB, then use it as normal until it changes itself to wide gamut, and grab a log using the built-in MatLog tool & attach it here, that would be awesome.

(There's a whole multi-year backstory I won't bore you with about display handling & ugly kernel hacks for oneplus/sdm845 that earlier & later OP phones didn't have to deal with, and this is true upstream in official LineageOS as well. The short version is "color modes suck on this phone, no matter what way you do it, unless you're running OOS 10 or 11 stock".)

**Comment by C-Ubermensch** [comment] 2023-11-14 11:14
In pixel experience, it doesn't switch, the white is very good, there's not
extra features at all but I don't really need them (but it's better to have
options but anyway),
So something like that.
Maybe u could kind get it fixed by using some code or something from pixel
experience idk, I'm not in it but it's kinda sad that such a good ROM as
crdroid make that issues with a such good phone like One plus 6. (I have
this photo 6-7 years i think and it serves me very well.

I did custo ROM because i was dead bored of it's system oxygen oc without
updates since never so something like that.

I appreciate what u do, it's cool that u have such a project like hobby,
it's really very cool.

I myself want to do something like that in the near future like music or
coding or painting…

Peace and luck to u terminator 👍⬇️

**Comment by Terminator-J** [comment] 2023-11-15 20:53
Thank you for the well-wishes, but... that also doesn't really help with troubleshooting, either.
Logs would've been useful, some troubleshooting info would've been useful.
Do you at least remember if it was specific apps that seemed to trigger the color mode switch?
Or do you even remember if you set sRGB within Settings > DIsplay > LiveDisplay?

On PixelExperience now, does LiveDisplay even exist, or do you just use the "Settings > DIsplay > Color" option now?
If they both exist, what mode do you choose in THAT one?

I really don't know what is so different in snnbyyds' trees that Pixel Experience seem to do it better...
- We're both using the same kernel commit stack (that I helped write!) including switching to OxygenOS panel color handling that EdwinMoq tried to bring back to oneplus/sdm845 a year or two ago (and makes DC Dimming look a lot better on enchilada to boot).
- We're both using the same modified color mode switching in LiveDisplay (again, including commits *I wrote*) based on sm8150 mode switching, in the device tree.

The big differences I can see are that 1) he imported some slightly-newer Qualcomm display-related vendor blobs from a different sdm845 device, and 2) added AOSP-style display mode color handling.
- I tested the newer blobs for a few months of crDroid releases, and got a lot more complaints again about problems with camera/gallery/google photos problems (image buffer incompatibilities or something)
- I made some test builds for myself that also have the combination of LiveDisplay for mode switching AND the AOSP color modes... I didn't use it long enough to notice anything about sRGB mode, but it seemed like it was both redundant and wouldn't be a great replacement for LiveDisplay color modes at the time.

So yeah. I have no idea; this is the first I've heard of that problem, and I don't really know where to go from here, since trying to incorporate the remaining color handling changes that PE uses seemed to cause other problems.
I might just give up on OOS-style display handling and go back to the hacky Lineage kernel implementation instead, just to keep my own sanity intact.

**Comment by C-Ubermensch** [comment] 2023-11-16 10:33
Do you at least remember if it was specific apps that seemed to trigger the
color mode switch?
Or do you even remember if you set sRGB within Settings > DIsplay >
LiveDisplay?

-What's interesting than after setting let's say sRGB after a while it
changes in gamut but if i restart the phone it goes to sRGB.
-Yeah, I've set sRGB within those setting, exactly the same.

On PixelExperience now, does LiveDisplay even exist, or do you just use the
"Settings > DIsplay > Color" option now?
If they both exist, what mode do you choose in THAT one?

- yeah it exists and it look the same as in crdroid
- the standard mode which is the same as dcip3 (good white, not
oversaturated color's, very pleasant to eyes)


I might just give up on OOS-style display handling and go back to the hacky
Lineage kernel implementation instead, just to keep my own sanity intact.

-idk man but if it's a hobby of your, issues must be the cherry on top
because it forces u outside of comfort zone to figure it out and make it
possible (at least I think like that)
- bugs don't suppose to happen, it means there's something going wrong with
something and needs fixing to have a whole picture, whole experience

I have some questions for u?
-why did u make the crdroid?
-what do u plan to do in the near future?
-whats your background?
What's your real name?

All of best 🫡

**Comment by C-Ubermensch** [comment] 2023-11-16 10:43
Also if it's possible, please increase the screen fps like 90, 120, 144 (to
be optional but default 90).

When i first saw a screen with like 120hz i was amazed how smooth it is, it
was something new to me (i knew that it's already kinda old technology but
it's amazing)

There's an option in crdroid and in pixel experience as week to increase
fps (force peak refres rate but it doesn't work), I can even tap to this
setting because the only way to see that this function like exists it's to
type in the settings search bar "refresh".

It doesn't work on both ROMs.

See ya 👋

**Comment by Terminator-J** [comment] 2023-11-16 16:19
Okay, confirmed with current users that sRGB mode gets changed unintentionally sometimes but then comes back after reboot (probably something between OOS-specific kernel code/vendor blobs and HWC requesting different colorspaces to do compositing in) just on the enchilada panel, but not on fajita.

I'll take a look and see if I can change behavior, either with the AOSP colorspace mapping in device tree, or dropping the extra kernel commits & livedisplay modifications.

Meanwhile, neither of the samsung panels used in the 6-series are designed for multiple or high refresh rates; they're physically 60Hz only. That's why you can't actually use the "force peak refresh" setting in Developer Options.
It's a hardware design limitation, not a bug or something that could be implemented in software.

I'm happy to chat more about unrelated stuff, but please reach out through XDA or Telegram (support forum link from crdroid.net website), rather than clutter this specific bug report.

**Comment by Terminator-J** [comment] 2023-11-17 23:32
I spent a day testing. No idea why it doesn't seem to happen on PE.
Reverted my kernel & device tree ocmmits to use OOS panel handling (same things that snnbyyds is using in Pixel Experience), and sticking with the Lineage kernel kludge instead, and not only does the issue appear to be resolved, but two OTHER longstanding issues (why I switched to OOS display handling in the first place) appear to have been resolved in the mean time.

¯\_(ツ)_/¯

Closing issue; bugfix will be part of 9.11 release.

**Closed by Terminator-J** 2023-11-17 23:32 UTC
Labels: bug, confirmed
