### ISSUE TITLE
bug: keyboard persists when exiting app drawer search bar using swipe gestures

### ISSUE THREAD

**Issue by vatski** [crdroidandroid/issue_tracker#25] opened 2022-10-30 14:24 UTC
### Issue type

User interface

### Device

alioth poco f3

### crDroid version

crDroid 8

### Bug description

When using swipe gestures to go to the home page from the app drawer the keyboard persists and will only go away with another home button swipe gesture.

### Steps to reproduce

Step 1: go to the app drawer
Step 2: pull up the keyboard be touching the search bar
Step 3: use the swipe gesture equivalent to pressing the home button
Step 4: the keyboard persists even after pressing outside it

### Relevant log (logcat/build log)

```shell
No crash report
```

### Screenshots or videos

https://drive.google.com/file/d/18PALvvbJbb489Ae-hELLwjrRyZ_uJ9a9/view?usp=drivesdk

### Solution

Swiping the equivalent home button removes the keyboard

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment] 2022-11-01 18:32
this seems to be more widespread
@crdroidandroid/coreteam ideas?
is logcat needed here ?

**Comment by xNombre** [comment] 2022-11-01 18:57
I would point at Launcher3. In LOS this issue is not present (Trebuchet).
After some research I found out it can be fixed by forcefully closing0 keyboard using hideKeyboard() method which is present in sources triggered by corresponding Android event.
However, a better idea is to git bisect and find the actual root cause. CC @neobuddy89

**Closed** 2023-01-15 08:41 UTC
Labels: bug
