### ISSUE TITLE
Navbar action button not working 

### ISSUE THREAD

**Issue by Moya78** [crdroidandroid/issue_tracker#115] opened 2023-02-03 12:06 UTC
### Issue type

Feature not working as intended

### Device

Alioth

### crDroid version

crDroid 9

### Exact version / Build date

9.1/2023-01-28

### Bug description

3 button Navigation bar action to open/close menu not working

### Steps to reproduce

CrDroid settings-Navigation-actions
Set any 3 button Navigation bar action either double tap or long press to open/close menu.

### Relevant log (logcat/build log)

```shell
Not applicable
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by raystef66** [comment] 2023-02-03 15:57
Tested and working here. Tested all 3 f.e. to open camera on longpress and double tap and working as intended.
Therefore I'll close the issue. If further assistance needed, I'll guide you to our TG group (if not yet joined) @crdroidf3

**Comment by Moya78** [comment] 2023-02-03 21:53
The issue is "open/close" menu action only.
All other actions are working fine.
Kindly check one last time.

**Comment by raystef66** [comment] 2023-02-04 09:34
Ah just misunderstood. Indeed opening/closing menu not working on any button.

**Comment by lindahl85** [comment] 2023-05-14 21:09
+1 on this issue:
crDroidAndroid-13.0-20230505-lemonadep-v9.5

**Comment by gwolf2u** [comment] 2023-08-17 17:14
#fixed in https://github.com/crdroidandroid/android_frameworks_base/pull/1019

**Closed by gwolf2u** 2023-08-17 17:14 UTC
Labels: bug
